spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 7000

upload:
  images_voiture: /Users/mac/Desktop/uploadFile/senlocationvoiture/images_voiture/
  images_profile: /Users/mac/Desktop/uploadFile/senlocationvoiture/images_profile/


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
