spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/car_location
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

upload:
  path:  /Users/mac/Desktop/uploadFile/